name: <project_name> CI Acceptance suite

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
      run: yarn --ignore-engines --silent --non-interactive
    - name: acceptance tests
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
      run: yarn test:acceptance
